sudo: required
services:
  - docker

before_install:
  - docker build -t airlangga07/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true airlangga07/react-test:latest npm run test

# do note that when you build and push docker image
# you need to specify the version as well
# otherwise it will failed to upload the image
after_success:
  - docker build -t airlangga07/multi-client:latest ./client
  - docker build -t airlangga07/multi-nginx:latest ./nginx
  - docker build -t airlangga07/multi-server:latest ./server
  - docker build -t airlangga07/multi-worker:latest ./worker

  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # take those images and push the to docker hub
  - docker push airlangga07/multi-client:latest
  - docker push airlangga07/multi-nginx:latest
  - docker push airlangga07/multi-server:latest
  - docker push airlangga07/multi-worker:latest

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-161045259490
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY