sudo: required
services:
  - docker

before_install:
  - docker build -t airlangga07/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true airlangga07/react-test:latest npm run test

after_success:
  - docker build -t airlangga07/multi-client:latest ./client
  - docker build -t airlangga07/multi-nginx:latest ./nginx
  - docker build -t airlangga07/multi-server:latest ./server
  - docker build -t airlangga07/multi-worker:latest ./worker

  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # take those images and push the to docker hub
  - docker push airlangga07/multi-client:latest
  - docker push airlangga07/multi-nginx:latest
  - docker push airlangga07/multi-server:latest
  - docker push airlangga07/multi-worker:latest