sudo: required
services:
  - docker

before_install:
  - docker build -t airlangga07:react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true airlangga07:react-test npm run test

after_success:
  - docker build -t airlangga07:multi-client ./client
  - docker build -t airlangga07:multi-nginx ./nginx
  - docker build -t airlangga07:multi-server ./server
  - docker build -t airlangga07:multi-worker ./worker

  # login to the docker cli
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io

  # take those images and push the to docker hub
  - docker push airlangga07:multi-client
  - docker push airlangga07:multi-nginx
  - docker push airlangga07:multi-server
  - docker push airlangga07:multi-worker