sudo: required
services:
  - docker

before_install:
  - docker build -t airlangga07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true airlangga07/react-test npm run test

after_success:
  - docker build -t airlangga07/multi-client ./client
  - docker build -t airlangga07/multi-nginx ./nginx
  - docker build -t airlangga07/multi-server ./server
  - docker build -t airlangga07/multi-worker ./worker

  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push the to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker